name: loop-run

on:
  workflow_dispatch: {}
  repository_dispatch:
    types: [rerun]

permissions:
  contents: write

concurrency:
  group: loop-run
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"   

      - name: Run loop (python -c, your code style)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p data

          start=$(date +%s)
          iter=0
          BRANCH="${GITHUB_REF_NAME:-${GITHUB_HEAD_REF:-main}}"

          while [ "$iter" -le 29164 ]; do
            iter=$((iter+1))
            ITER="$iter" python -c $'from pathlib import Path\nimport os\nimport pandas as pd\nimport requests\nprint("Hello,World!")\n'



          done

      - name: Re-dispatch self
        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_DISPATCH }}   # PAT with 'repo' scope
        run: |
          curl -s -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/dispatches" \
            -d '{"event_type":"rerun"}'
