name: loop-run

on:
  workflow_dispatch: {}  
  repository_dispatch:   
    types: [rerun]

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          
      - uses: actions/setup-python@v5
        with: { python-version: "3.13.7" }

      - name: Run loop
        run: |
          set -euo pipefail
          start = $(date +%s)
          iter = 0
          while [$(($(date+%s)-start)) -lt $((60*340))]; do
            iter = $((iter+1))
            
            ITER = "$iter" python - << 'PY'
            from pathlib import Path
            import os
            iter_val = int(os.environ["ITER"])
            p = Path("data/test.txt")
            fi = open(p,mode='w')
            fi.write(str(iter_val))
            fi.close()
            PY
            
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/test.txt
            git commit -m "tick: $(date -u +%Y-%m-%dT%H:%M:%SZ) (iter $iter)" || true
            git pull --rebase --autostash origin "${GITHUB_REF_NAME:-$GITHUB_REF##refs/heads/}" || true
            git push || true
            sleep 10
          done

      - name: Re-dispatch self
        env:
          GH_TOKEN: ${{ secrets.PAT_FOR_DISPATCH }}
        run: |
          curl -s -X POST \
            -H "Authorization: token ${GH_TOKEN}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"rerun"}'
